name: traction_timer
description: Pull-up & calisthenics pyramid timer with smart rest and optional TTS voice.
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  go_router: ^13.2.0
  shared_preferences: ^2.2.3
  flutter_tts: ^4.0.2
  uuid: ^4.4.0
  file_selector: ^1.1.0
  path_provider: ^2.1.5
  youtube_player_flutter: ^9.1.3
  video_player: ^2.9.1
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

  fake_async: any
  path_provider_platform_interface: ^2.1.2
  plugin_platform_interface: ^2.1.8
flutter:
  uses-material-design: true
